#my.datasource.url=local.db.com
#my.datasource.username=local_user
#my.datasource.password=local_pw
#my.datasource.etc.max-connection=1
#my.datasource.etc.timeout=3500ms
#my.datasource.etc.options=CACHE,ADMIN

my:
  datasource:
    url: local.db.com
    username: local_user
    password: local_pw
    etc :
      max-connection: 1
      timeout: 3500ms
      options: CACHE,ADMIN